[env:nucleo_wl55]
extends = stm32_base
board = nucleo_wl55jc
board_level = pr
board_upload.maximum_size = 233472 ; reserve the last 28KB for filesystem
build_flags =
  ${stm32_base.build_flags}
  -Ivariants/stm32/nucleo_wl55
  -DNUCLEOWL55
  -DMESHTASTIC_EXCLUDE_ENVIRONMENTAL_SENSOR=1
  -DMESHTASTIC_EXCLUDE_I2C=1
  -DMESHTASTIC_EXCLUDE_GPS=1
  -DHAVE_HWSERIAL2

upload_protocol = stlink
